### ISSUE TITLE
[JENKINS] Committer does not exists

### ISSUE THREAD

**Issue by syky27** [3DprintFIT/BI-3DT#78]

**Comment by hroncok** [comment]
You are leaking tokens.

**Comment by hroncok** [comment]
The Solution repo does not exist and it never had. This is a valid failure, not an error.

**Comment by syky27** [comment]
Yes this is, my bad...

**Comment by syky27** [comment]
But this ain't

```
Test repo not cloned yet, this is first run.
{'title': 'Your username', 'markdowns': ['Your username is preneond.'], 'labels': ['success'], 'exitcode': 0}
Traceback (most recent call last):
  File "/usr/local/bin/lab_test_runner", line 205, in <module>
    post_github_issue(results)
  File "/usr/local/bin/lab_test_runner", line 161, in post_github_issue
    'assignee': get_assignee()
  File "/usr/local/bin/lab_test_runner", line 120, in get_assignee
    commiter = r.json()[0]['author']['login']
TypeError: 'NoneType' object is not subscriptable
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline

```

**Comment by syky27** [comment]
The committer does not exists for some reason https://github.com/3DprintFIT/B171AS-Username-preneond

**Comment by syky27** [comment]
it actually exists but the author of last commit in api is none... https://github.com/preneond
